#!/usr/bin/env bun
/**
 * Compiles the authored ARB catalogs in src/i18n/*.arb into typed TypeScript
 * modules. Translators edit ARB; nothing reads ARB at runtime.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Part } from "../src/i18n/catalog-contract";
import { argNames, parseMessage } from "../src/i18n/message-parser";

const I18N_DIR = join(import.meta.dir, "..", "src", "i18n");
const OUT_DIR = join(I18N_DIR, "generated");
const REFERENCE_LOCALE = "en";
const HEADER = "// Generated by scripts/build-messages.ts from src/i18n/*.arb. Do not edit.\n";

type Meta = { description?: string; placeholders?: Record<string, { type?: string }> };

function symbol(locale: string): string {
  return `${locale.toUpperCase().replace(/-/g, "_")}_MESSAGES`;
}

function readArb(locale: string): { messages: Record<string, string>; meta: Record<string, Meta> } {
  const raw = JSON.parse(readFileSync(join(I18N_DIR, `${locale}.arb`), "utf8")) as Record<string, unknown>;
  const messages: Record<string, string> = {};
  const meta: Record<string, Meta> = {};
  for (const [key, value] of Object.entries(raw)) {
    if (key === "@@locale") continue;
    if (key.startsWith("@")) meta[key.slice(1)] = value as Meta;
    else messages[key] = value as string;
  }
  return { messages, meta };
}

const locales = readdirSync(I18N_DIR)
  .filter((name) => name.endsWith(".arb"))
  .map((name) => name.slice(0, -".arb".length))
  .sort((a, b) => (a === REFERENCE_LOCALE ? -1 : b === REFERENCE_LOCALE ? 1 : a.localeCompare(b)));
if (!locales.includes(REFERENCE_LOCALE)) throw new Error(`missing ${REFERENCE_LOCALE}.arb`);

const reference = readArb(REFERENCE_LOCALE);
const referenceKeys = Object.keys(reference.messages);
const referenceArgs = new Map<string, Set<string>>(
  referenceKeys.map((key) => [key, argNames(parseMessage(reference.messages[key]))]),
);

const errors: string[] = [];
const parsed = new Map<string, Record<string, Part[]>>();

for (const locale of locales) {
  const { messages } = readArb(locale);
  const byKey: Record<string, Part[]> = {};
  for (const key of referenceKeys) {
    const raw = messages[key];
    if (raw === undefined) {
      errors.push(`${locale}.arb: missing key "${key}"`);
      continue;
    }
    try {
      const parts = parseMessage(raw);
      const expected = referenceArgs.get(key) ?? new Set<string>();
      const actual = argNames(parts);
      for (const name of actual)
        if (!expected.has(name)) errors.push(`${locale}.arb: ${key}: unknown placeholder "{${name}}"`);
      for (const name of expected)
        if (!actual.has(name)) errors.push(`${locale}.arb: ${key}: missing placeholder "{${name}}"`);
      byKey[key] = parts;
    } catch (error) {
      errors.push(`${locale}.arb: ${key}: ${error instanceof Error ? error.message : String(error)}`);
    }
  }
  for (const key of Object.keys(messages)) {
    if (!referenceArgs.has(key)) errors.push(`${locale}.arb: unknown key "${key}" (not in ${REFERENCE_LOCALE}.arb)`);
  }
  if (reference.meta && locale === REFERENCE_LOCALE) {
    for (const key of referenceKeys) {
      const description = reference.meta[key]?.description;
      if (!description || description === "TODO") errors.push(`${locale}.arb: ${key}: missing @${key}.description`);
    }
  }
  parsed.set(locale, byKey);
}

if (errors.length) {
  for (const line of errors) console.error(`error  ${line}`);
  console.error(`\n${errors.length} message error(s).`);
  process.exit(1);
}

for (const locale of locales) {
  const body = referenceKeys
    .map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(parsed.get(locale)?.[key])},`)
    .join("\n");
  writeFileSync(
    join(OUT_DIR, `${locale}.ts`),
    `${HEADER}import type { Message } from "../catalog-contract";\n\nexport const ${symbol(locale)} = {\n${body}\n} satisfies Record<string, Message>;\n`,
  );
}

const argsEntries = referenceKeys
  .map((key) => {
    const names = [...(referenceArgs.get(key) ?? new Set<string>())].sort();
    if (!names.length) return `  ${JSON.stringify(key)}: never;`;
    const fields = names
      .map(
        (name) =>
          `${name}: ${reference.meta[key]?.placeholders?.[name]?.type === "number" ? "number" : "string | number"}`,
      )
      .join("; ");
    return `  ${JSON.stringify(key)}: { ${fields} };`;
  })
  .join("\n");

writeFileSync(
  join(OUT_DIR, "catalogs.ts"),
  `${HEADER}${locales.map((locale) => `import { ${symbol(locale)} } from "./${locale}";`).join("\n")}\n\nexport const TRANSLATIONS = {\n${locales
    .map((locale) => `  ${JSON.stringify(locale)}: ${symbol(locale)},`)
    .join("\n")}\n} as const;\n\nexport const LOCALES = [${locales
    .map((locale) => JSON.stringify(locale))
    .join(", ")}] as const;\n\nexport type MessageArgs = {\n${argsEntries}\n};\n`,
);

console.log(`messages: ${referenceKeys.length} | locales: ${locales.join(", ")}`);
