import { z } from "zod";

export const terminalStyleRoleSchema = z.enum([
  "plain",
  "muted",
  "subtle",
  "faint",
  "user",
  "assistant",
  "assistant-code",
  "assistant-bold",
  "assistant-path",
  "syntax-plain",
  "syntax-keyword",
  "syntax-string",
  "syntax-comment",
  "syntax-number",
  "syntax-type",
  "syntax-function",
  "syntax-property",
  "syntax-meta",
  "tool",
  "skill-on",
  "skill-off",
  "pending",
  "pending-dim",
  "pending-shimmer",
  "pending-shimmer-mid",
  "pending-shimmer-bright",
  "queued",
  "accepted",
  "success",
  "warning",
  "error",
  "cancelled",
  "diff-added",
  "diff-removed",
  "user-fill",
  "composer-border",
  "composer-prompt",
  "ghost",
  "selected",
  "pr-open",
  "pr-merged",
  "pr-closed",
  "tool-label",
  "tool-meta-add",
  "tool-meta-remove",
  "header-brand",
  "header-mascot",
  "header-eyes",
  "cursor",
]);
export type TerminalStyleRole = z.infer<typeof terminalStyleRoleSchema>;

export const terminalStyleSchema = z.object({
  foreground: z.string().optional(),
  background: z.string().optional(),
  bold: z.boolean().optional(),
  dim: z.boolean().optional(),
  inverse: z.boolean().optional(),
});
export type TerminalStyle = z.infer<typeof terminalStyleSchema>;

export const terminalThemeSchema = z.object({ styles: z.record(terminalStyleRoleSchema, terminalStyleSchema) });
export type TerminalTheme = z.infer<typeof terminalThemeSchema>;

export const terminalTheme: TerminalTheme = Object.freeze({
  styles: {
    plain: {},
    muted: { dim: true },
    subtle: { foreground: "#999999" },
    faint: { foreground: "#666666" },
    user: { foreground: "#ffffff" },
    assistant: { foreground: "#ffffff" },
    "assistant-code": { foreground: "#4DA3FF" },
    "assistant-bold": { foreground: "#ffffff", bold: true },
    "assistant-path": { foreground: "#ffffff", dim: true },
    // Foreground-only (no code-block band), built from Acolyte's own accent hues so code speaks the
    // same palette as the markers and chrome: keyword = brand, function = the pending-blue marker,
    // string = the queued-gold marker. `type` sits a step green of the accepted-cyan marker and
    // `meta` a step pink of the brand so the type/function blues and the keyword/decorator purples
    // stay distinct. Plain and comment stay calm (near-white / recessed grey) so the vivid tokens
    // read against a restful base, not as noise.
    "syntax-plain": { foreground: "#ECF2FB" },
    "syntax-keyword": { foreground: "#A56EFF" },
    "syntax-string": { foreground: "#F5C451" },
    "syntax-comment": { foreground: "#999999" },
    "syntax-number": { foreground: "#FF7A5C" },
    "syntax-type": { foreground: "#4BE0B0" },
    "syntax-function": { foreground: "#4DA3FF" },
    "syntax-property": { foreground: "#9EE86B" },
    "syntax-meta": { foreground: "#E07BD0" },
    tool: { foreground: "#aaaaaa" },
    "skill-on": { foreground: "#A56EFF" },
    "skill-off": { dim: true },
    pending: { foreground: "#4DA3FF" },
    "pending-dim": { foreground: "#4DA3FF", dim: true },
    "pending-shimmer": { foreground: "#666666" },
    "pending-shimmer-mid": { foreground: "#808080" },
    "pending-shimmer-bright": { foreground: "#999999" },
    queued: { foreground: "#F5C451" },
    accepted: { foreground: "#4DD2FF" },
    success: { foreground: "green" },
    warning: { foreground: "#d29922" },
    error: { foreground: "red" },
    cancelled: { foreground: "#E5A84B" },
    "diff-added": { foreground: "#4a9a4a", background: "#042208" },
    "diff-removed": { foreground: "#9a4a4a", background: "#2a0606" },
    "user-fill": { background: "#1c1c26" },
    "composer-border": { foreground: "#A56EFF", dim: true },
    "composer-prompt": {},
    ghost: { foreground: "#666666" },
    selected: { foreground: "#A56EFF" },
    "pr-open": { foreground: "green", dim: true },
    "pr-merged": { foreground: "magenta", dim: true },
    "pr-closed": { foreground: "red", dim: true },
    "tool-label": { bold: true },
    "tool-meta-add": { foreground: "#4a9a4a" },
    "tool-meta-remove": { foreground: "#9a4a4a" },
    "header-brand": { foreground: "#A56EFF" },
    "header-mascot": { foreground: "#2A1D4A" },
    "header-eyes": { foreground: "#FFD84D" },
    cursor: { inverse: true },
  },
});
